-- This module is the root of the ErdosGyarfasConjectureCanonicalLaneLean Lean proof package.
import ErdosGyarfasConjectureCanonicalLaneLean.Basic
import ErdosGyarfasConjectureCanonicalLaneLean.SourcePackage
import ErdosGyarfasConjectureCanonicalLaneLean.SourceDependencies
import ErdosGyarfasConjectureCanonicalLaneLean.Formalization
import ErdosGyarfasConjectureCanonicalLaneLean.ReviewerBridge
import ErdosGyarfasConjectureCanonicalLaneLean.TheoremStatement
import ErdosGyarfasConjectureCanonicalLaneLean.MathlibObjects
import ErdosGyarfasConjectureCanonicalLaneLean.AdmissibleClass
import ErdosGyarfasConjectureCanonicalLaneLean.Projection
import ErdosGyarfasConjectureCanonicalLaneLean.BridgeLemmas
import ErdosGyarfasConjectureCanonicalLaneLean.GateLemmas
import ErdosGyarfasConjectureCanonicalLaneLean.FinalTheorem
import ErdosGyarfasConjectureCanonicalLaneLean.MathlibStatement
